version: '3.5'
services:
  redis:
    restart: always
    image: redis:latest
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    ports:
     - "6379:6379"
    environment:     
     - SERVICE_NAME=redis
     - SERVICE_TAGS=db,redis
     - SERVICE_REGION=DC1